version: '3.8'

services:
  # Сервис базы данных
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: 12321
      POSTGRES_DB: todo_db
    ports:
      - "2211:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d  # Автоматическое применение миграций
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Сервис нашего приложения
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: 12321
      DB_SSLMODE: disable
      SERVER_PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/root/static  # Монтируем статические файлы

volumes:
  postgres_data: